### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gimm**
change step #4 within Manual install, should create a file without .sublime-theme

### CODE REVIEW

**Comment by adibbehjat** [comment]
+1 on this request

**Comment by LeeMing988** [comment]
how come my images is not preview after i follow all of the step.....hmm this is weird

**Comment by chrise86** [comment]
I can't get this to work at all, with or without the extension. Using Space Gray (Space Gray Eighties).

**Comment by marcofugaro** [comment]
@chrise86 I implemented these icons and some more on SpaceGray, download this and enable it in the settings of sublime https://github.com/marcofugaro/spacegray/tree/betterfileicons

**Comment by ko-dever** [comment]
Can you give a more detailed how-to please, I cannot get this to work.

Theme - Spacefunk
Spacefunk (Blue Monday)
https://packagecontrol.io/packages/Theme%20-%20Spacefunk

3/ rename the unzipped folder to the exact name of your current theme's parent folder, for example "Theme - Soda" ==> Theme - Spacefunk
4/ If your theme is Soda Dark 3, then create a new file called "Soda Dark 3.sublime-theme" (==> Spacefunk (Blue Monday).sublime-theme) in the newly downloaded directory (Theme - Spacefunk folder of step 3).

Nothing happens.

**Comment by utkjad** [comment]
+1 for updating instructions as well. 
What do we do when we have inbuilt theme (example - Cobalt in my case)?

**Comment by sebastian-palma** [comment]
Just finished of setting it in Debian, this works like that:

1.- Download zip
2.- Extract into  ~/.config/sublime-text-3/Packages/User/
3.- Rename the extracted file:
  If you're using a theme called 'Theme - Brogrammer' with path
  ~/.config/sublime-text-3/Packages/Theme - Brogrammer
  then the extracted zip should be
  ~/.config/sublime-text-3/Packages/User/Theme - Brogrammer
4.- Search into the theme folder a file called as 'name_of_your_theme.sublime-theme'
5.- Copy the previous file into '~/.config/sublime-text-3/Packages/User/Theme -     Brogrammer/<name_of_your_theme.sublime-theme>' and paste this inside:

```
[
   {
      "class": "icon_file_type",
      "content_margin": [8,8]
   }
]
```

**Comment by utkjad** [comment]
@LagartoSeb - I am using `sublime text 3` with just `cobalt` color scheme. in `Windows 764 bit`
Relevant content in `settings-users`

```
"color_scheme": "Packages/Color Scheme - Default/Cobalt.tmTheme",
```

Note - Strange it is that I do not have `~\AppData\Roaming\Sublime Text 3\Packages\Color Scheme` folder. or `Cobalt.tmTheme` or `*.sublime-theme` in `~\AppData\~` directory
Do we have to have a customized theme in order to make this work?

**Pull request merged**
